---
namespace: wheecious
name: kener
version: 0.1.0
readme: README.md
authors:
  - wheecious (github.com/wheecious)
description: Ansible modules for kener.
tags: kener
repository: https://github.com/wheecious/kener/
