---
namespace: wheecious
name: kener
version: 0.1.1
readme: README.md
authors:
  - wheecious (github.com/wheecious)
description: Ansible modules for kener.
tags: kener
license: MIT
repository: https://github.com/wheecious/kener
